#!/usr/bin/env bash


# Running lints, test, build
echo -e "\n\
======================================\n\
          Running python test         \n\
======================================\n";

pytest


